name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace --info --no-daemon || ./gradlew build --stacktrace --info --no-daemon
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuperbWarfare-Fabric-1.21.1
          path: build/libs/*.jar
